### ISSUE TITLE
wallet ui transaction FEE incorrect?

### ISSUE THREAD

**Issue by petjal** [Blockstream/green_android#125] opened 2021-08-12 03:34 UTC
### Description

Sorry, new to all this, maybe I'm mistaken about something, but on my phone, in the Green wallet app, tap my wallet, tap my new incoming transaction, I see it "Completed", I see the correct "AMOUNT" of BTC, but the FEE shown is way more than I lost during the send from my exchange account.  The FEE shown is the fee for the whole outbound transaction from the exchange to a few dozen addresses.  I think I paid a low 0.1% fee, but the UI seems to indicate that I paid a high 4.1%. 

### Version

Green Version 3.6.4 release

### Steps to reproduce

See above. 

### Expected behaviour

See above.

### Actual behaviour

See above. 

### Screenshots

![FEE](https://user-images.githubusercontent.com/3526136/129134218-b18cb70a-0ec7-479f-b7d9-0dbc60da1d44.png)

### Device or machine

Google Pixel 3a, Android 11

### Additional info

n/a

**Comment by jgriffiths** [comment] 2021-08-12 22:38
Hi @petjal 

The fee shown here is the miner fee of the whole transaction as stored in the blockchain.

For an outgoing transaction (i.e. a payment you sent) the fee will always be exactly what you paid, since the transaction only has your payment in it.

For an incoming transaction (i.e. a payment you received), the fee is what the *sender* (coinbase in this case) paid in fees. Since the sender paid the fee, and because they may have batched up several other payments into the same transaction, this doesn't tell you anything about what you paid coinbase as a withdrawwl fee. For incoming transactions, the fee is shown for your information, but the amount shown there is not deducted from your balance, since you didn't pay it, the sender (coinbase) did.

Whatever fee coinbase charges for withdrawal will be reflected in the amount they paid you; this information is private between you and coinbase and they will have deducted it either from your remaining balance on coinbase or from the amount sent (i.e. the amount shown as received will be smaller that you withdrew as they kept some value for the fee). Coinbase help can presumably tell you which of these approaches they use when you withdraw.

Hope this helps, closing this as its not a bug.

**Closed by jgriffiths** 2021-08-12 22:38 UTC
