### ISSUE TITLE
Misleading "PIN error" when internet connection is disabled

### ISSUE THREAD

**Issue by jsarenik** [Blockstream/green_android#128] opened 2021-10-26 09:27 UTC
### Description

On someone else's Android phone with the latest Blockstream Green app I have seen that they received "PIN error" but it was actually a missing connection (WiFi and data were turned off, after turning WiFi on, the error disappeared).

### Version

Will write more details when I manage to reproduce the error.

### Steps to reproduce

 1. While connected to internet: Set up a testnet wallet. Set PIN to 123456.
 2. Disconnect from internet. "Stop" the app (in the app history swipe it away.)
 3. Turn on the app. Try to log into the testnet wallet.

### Expected behaviour

Something like `Error: Unable to connect.`

### Actual behaviour

`PIN error`

### Device or machine

The device I saw it on was some recent Samsung Android smartphone.

**Comment by sgornick** [comment] 2021-11-05 05:29
I can confirm this behavior.

For me, the expected behavior was for the app to check connectivity before requesting the PIN and show an error at that point in time.

**Comment by paulkania** [comment] 2022-02-11 19:38
I can also confirm this behavior and add that:
iOS error handle is : login failed (iPhone 8+ running 14.7.1)
Android error : Pin error (Alcatel tablet running Android 7.1.1)

Also: on both platforms unlimited login attempts are available without timeouts, which is a good thing imo, since the server isn't reached, the attempts aren't valid to begin with.

**Comment by angelix** [comment] 2022-03-03 08:52
Fixed in https://github.com/Blockstream/gdk/commit/8d5f9a24388289030e10c984b0d1eaa8efba1a73
Probably, fix will be included in `3.8.1`

**Closed by angelix** 2022-03-03 08:52 UTC
