### ISSUE TITLE
Personal Electrum Server dialogue box missing & disparity between android and iOS platforms

### ISSUE THREAD

**Issue by paulkania** [Blockstream/green_android#135] opened 2022-02-12 21:52 UTC
### Description

Android Green users cannot connect to the liquid **mainnet** via a Personal Electrum Server (PES). The requisite dialogue box does not appear.
iOS Green users, similarly, cannot connect to the liquid **testnet** via the PES. 
Put another way, there are four PES servers ultimately reachable: i) mainnet ii) testnet iii) liquid mainnet iv) liquid testnet, each with their respective blockstream.info:### ports 
On Android i) ii) iv) are accessible. 
On  -- iOS  -  i) ii) iii) are accessible.

### Version

Android - 3.7.8 - Alcatel tablet running android 7.1.1
IOS - 3.7.8 - iphone 8+ running 14.7.1

### Steps to reproduce

On Android
1. Enable PES - You will notice PES options now include i) mainnet. iii) liquid mainnet - **is not included.**
2. Enable testnet - Notice  PES options still include i) and also include ii) testnet and iv) liquid testnet, but not iii) liquid mainnet.

On iOS

1. Enable PES - You will notice PES Options now  include i) mainnet **and** iii) Liquid mainnet.
2. Enable testnet - Notice  Options include i) iii)  as well as ii) testnet, but not iv) liquid testnet.

### Expected behaviour

1. Design choice is not mine to make regarding whether liquid testnet should be available on the green wallets. However, Android and iOS should present the same PES dialogue boxes, either both should present i,ii,iii,iv or just i,ii,iii if liquid testnet is to be excluded.

### Actual behaviour

See 'Steps to reproduce' 

### Screenshots

![iOS-PES-issue](https://user-images.githubusercontent.com/4791983/153729032-45dda6b6-ab1d-472c-83c8-d491f52d1e54.jpeg)

### Device or machine

IOS - 3.7.8 - iphone 8+ running 14.7.1
Android - 3.7.8 - Alcatel tablet running android 7.1.1

### Additional info

I am still new to the codebase, but the fix may be in /green/src/main/java/com/blockstream/green/settings/ApplicationSettings.kt

**Comment by lvaccaro** [comment] 2022-02-28 15:19
Hi @paulkania , thanks for the report.
On green android, the issue is fixed in commit e4367921ee479fe85856b43582f6bd82764baadf which is included in the latest green android release v3.7.9 . Thanks track the issue on the codebase.
On green iOS, the issue is still on working in progress, and it will be available on the next release.

**Comment by paulkania** [comment] 2022-02-28 15:37
yes i noticed commit e436... glad it was an easy fix.

**Closed** 2022-04-17 00:06 UTC
