### ISSUE TITLE
Stuck at verify PIN step. 

### ISSUE THREAD

**Issue by Transisto** [Blockstream/green_android#22] opened 2019-03-26 03:58 UTC
version 3.0.7

I get asked to verify PIN, after last digit nothing happen.

I'm sure the verified PIN is good as when entering the wrong PIN it say so.

There should also be a way to back if PIN was wrong

**Comment by Transisto** [comment] 2019-03-26 04:08
I started again a wallet creation process and instead of nothing happening I get a green spinner than last about 1min. Then I'm back at same stage.

Press back to erase one digit then type last digit again to get a "Congratulation wallet ready to use"

**Comment by domegabri** [comment] 2019-03-26 13:39
I get similar behavior doing the following:

- create new wallet
- set pin
- turn off wifi
- verify pin

**Comment by gitfede** [comment] 2019-04-23 12:38
The Green app (v. 3.1.0) crashes after entering the PIN.
![Screenshot_2019-04-23_14-25-08](https://user-images.githubusercontent.com/39822590/56581484-54673480-65d5-11e9-915e-05a42fdc8d16.png)
![Screenshot_2019-04-23_14-23-56](https://user-images.githubusercontent.com/39822590/56581490-5b8e4280-65d5-11e9-9ad4-442d48d56b73.png)

**Comment by domegabri** [comment] 2019-04-26 10:01
@gitfede was this problem also reproducible in any of the previous versions? can you reproduce in 3.1.1?

**Comment by gitfede** [comment] 2019-04-26 18:02
v. 3.1.1 when available in F-Droid?

**Comment by codeista** [comment] 2019-04-29 10:28
Seems that GDK is crashing when connecting, heres the logcat and stack trace:

04-29 13:48:59.964   824  1261 I ActivityManager: Start proc 2367:com.greenaddress.greenbits_android_wallet/u0a125 for activity com.greenaddress.greenbits_android_wallet/com.greenaddress.greenbits.ui.PinActivity
04-29 13:49:00.193  2367  2367 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10125 <<<<<<
04-29 13:49:00.320  2367  2367 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
04-29 13:49:00.320  2367  2367 D Zygote  : begin preload
04-29 13:49:00.341  2367  2367 I Zygote  : Preloading shared libraries...
04-29 13:49:00.438  2367  2367 D Zygote  : end preload
04-29 13:49:00.526  2367  2367 I MultiDex: VM with version 2.1.0 has multidex support
04-29 13:49:00.526  2367  2367 I MultiDex: Installing application
04-29 13:49:00.526  2367  2367 I MultiDex: VM has multidex support, MultiDex support library is disabled.
04-29 13:49:00.562  2367  2367 I com.greenaddress.greenbits_android_wallet: Thread[1,tid=2367,Native,Thread*=0x6af835e620,peer=0x12c01d00,"main"] recursive attempt to load library "/data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/lib/arm64/libgreenaddress.so"
04-29 13:49:00.612  2367  2367 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
04-29 13:49:00.612  2367  2367 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
04-29 13:49:00.612  2367  2367 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
04-29 13:49:00.634  2367  2406 D libEGL  : loaded /vendor/lib64/egl/libEGL_adreno.so
04-29 13:49:00.649  2367  2406 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
04-29 13:49:00.688  2367  2406 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_adreno.so
04-29 13:49:00.696  2367  2407 D OpenGLRenderer: HWUI GL Pipeline
04-29 13:49:00.711  2367  2367 W Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
04-29 13:49:00.810  2367  2407 I Adreno  : QUALCOMM build                   : 2941438, I916dfac403
04-29 13:49:00.810  2367  2407 I Adreno  : Build Date                       : 10/03/17
04-29 13:49:00.810  2367  2407 I Adreno  : OpenGL ES Shader Compiler Version: EV031.21.02.00
04-29 13:49:00.810  2367  2407 I Adreno  : Local Branch                     : O18A
04-29 13:49:00.810  2367  2407 I Adreno  : Remote Branch                    :
04-29 13:49:00.810  2367  2407 I Adreno  : Remote Branch                    :
04-29 13:49:00.810  2367  2407 I Adreno  : Reconstruct Branch               :
04-29 13:49:00.815  2367  2407 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
04-29 13:49:00.823  2367  2407 I com.greenaddress.greenbits_android_wallet: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-29 13:49:00.825  2367  2407 I OpenGLRenderer: Initialized EGL, version 1.4
04-29 13:49:00.825  2367  2407 D OpenGLRenderer: Swap behavior 2
04-29 13:49:08.026  2367  2583 F libc    : Fatal signal 11 (SIGSEGV), code 2, fault addr 0x6a651055b0 in tid 2583 (pool-1-thread-1), pid 2367 (_android_wallet)
04-29 13:49:08.092   710   710 I /system/bin/tombstoned: received crash request for pid 2367
04-29 13:49:08.093  2686  2686 I crash_dump64: performing dump of process 2367 (target tid = 2583)
04-29 13:49:08.093  2686  2686 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-29 13:49:08.093  2686  2686 F DEBUG   : Build fingerprint: 'Android/aosp_sailfish/sailfish:8.1.0/OPM4.171019.021.D1/2018.06.05.00:user/release-keys'
04-29 13:49:08.093  2686  2686 F DEBUG   : Revision: '0'
04-29 13:49:08.093  2686  2686 F DEBUG   : ABI: 'arm64'
04-29 13:49:08.093  2686  2686 F DEBUG   : pid: 2367, tid: 2583, name: pool-1-thread-1  >>> com.greenaddress.greenbits_android_wallet <<<
04-29 13:49:08.093  2686  2686 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6a651055b0
04-29 13:49:08.093  2686  2686 F DEBUG   :     x0   0000000000000000  x1   0000006af6d567d5  x2   0000000000000000  x3   0000006a5f87e3e0
04-29 13:49:08.093  2686  2686 F DEBUG   :     x4   0000006a68f3da80  x5   0000000080000000  x6   0000006af8813000  x7   0000000000000000
04-29 13:49:08.093  2686  2686 F DEBUG   :     x8   0000000000000b40  x9   0000000000000000  x10  0000000000000b40  x11  0000000000000000
04-29 13:49:08.093  2686  2686 F DEBUG   :     x12  02f2addf02513fb9  x13  0000000000000004  x14  0000000000000004  x15  0000000000000044
04-29 13:49:08.093  2686  2686 F DEBUG   :     x16  0000006af6d713a0  x17  0000006af6cfac68  x18  00000000ff27736b  x19  0000006a651055b0
04-29 13:49:08.093  2686  2686 F DEBUG   :     x20  0000000000000000  x21  000000000000006e  x22  0000000000000002  x23  0000000000000089
04-29 13:49:08.093  2686  2686 F DEBUG   :     x24  0000000000000062  x25  00000000ffffffff  x26  0000006a5f87e730  x27  0000000013017490
04-29 13:49:08.093  2686  2686 F DEBUG   :     x28  0000000000000000  x29  0000006a5f87e680  x30  0000006af6d3ebf8
04-29 13:49:08.093  2686  2686 F DEBUG   :     sp   0000006a5f87e600  pc   0000006af6d3ec30  pstate 0000000040000000
04-29 13:49:08.098  2686  2686 F DEBUG   :
04-29 13:49:08.098  2686  2686 F DEBUG   : backtrace:
04-29 13:49:08.098  2686  2686 F DEBUG   :     #00 pc 000000000006cc30  /system/lib64/libc.so (__pthread_mutex_lock_with_timeout(pthread_mutex_internal_t*, bool, timespec const*)+224)
04-29 13:49:08.098  2686  2686 F DEBUG   :     #01 pc 000000000028ce18  /data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/lib/arm64/libgreenaddress.so (offset 0x250000) (std::__ndk1::mutex::lock()+8)
04-29 13:49:08.098  2686  2686 F DEBUG   :     #02 pc 00000000004c76bc  /data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/lib/arm64/libgreenaddress.so (offset 0x250000)
04-29 13:49:08.098  2686  2686 F DEBUG   :     #03 pc 00000000002ec12c  /data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/lib/arm64/libgreenaddress.so (offset 0x250000) (GA_connect+332)
04-29 13:49:08.098  2686  2686 F DEBUG   :     #04 pc 00000000004e4168  /data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/lib/arm64/libgreenaddress.so (offset 0x250000) (Java_com_blockstream_libgreenaddress_GDK_connect+476)
04-29 13:49:08.098  2686  2686 F DEBUG   :     #05 pc 000000000055bb60  /data/app/com.greenaddress.greenbits_android_wallet-TbBGTVQLgrSsoJ67kSYbTw==/oat/arm64/base.odex (offset 0x398000)
04-29 13:49:08.093  2686  2686 F DEBUG   : pid: 2367, tid: 2583, name: pool-1-thread-1  >>> com.greenaddress.greenbits_android_wallet <<<
04-29 13:49:08.732   824   880 W zygote64: kill(-2367, 9) failed: No such process
04-29 13:49:08.732   824   861 I ActivityManager: Process com.greenaddress.greenbits_android_wallet (pid 2367) has died: fore TOP
04-29 13:49:08.748   615   615 I Zygote  : Process 2367 exited due to signal (11)
04-29 13:49:08.755   824   893 W ActivityManager: setHasOverlayUi called on unknown pid: 2367
04-29 13:49:08.777   824   880 W zygote64: kill(-2367, 9) failed: No such process                                                                                                            
04-29 13:49:08.777   824   880 I zygote64: Successfully killed process cgroup uid 10125 pid 2367 in 45ms


From the stack trace, it seems its trying to lock a mutex that has been deleted or not initialised/created.

**Comment by gitfede** [comment] 2019-05-03 10:04
I just installed Green v. 3.1.2 from F-Droid and the login does not work and the app crashes.

**Comment by gitfede** [comment] 2019-05-19 14:19
unable again to login with v. 3.1.3

**Comment by domegabri** [comment] 2019-05-30 09:37
Hello @gitfede , we have introduced a fix for this issue  that is affecting a substancial number of users. It will be available in the next relase.

**Comment by alessandro-saglimbeni** [comment] 2019-07-24 13:43
Hello @gitfede @codeista was this bug fixed?

**Comment by gitfede** [comment] 2019-07-26 20:50
The last release is always 3.1.3 of 2019-05-15 and still does not work, I am waiting for the next release. Thank you

**Comment by gitfede** [comment] 2019-07-31 12:27
today with the new version of Green 3.1.9, I can login!

**Comment by domegabri** [comment] 2019-07-31 15:58
Closing for now. @codeista  let us know if you are still having problems after upgrading to 3.1.9

**Closed by domegabri** 2019-07-31 15:58 UTC
Labels: bug, monitoring
