### ISSUE TITLE
Can't scroll up if I use the the finger in the black space.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#4] opened 2019-03-20 12:46 UTC
Hi, when I scroll down the transaction list and want to go back to top, sometimes what I see is the refresh function. But what I would like is go to top of window, to see the card.

**Comment by alessandro-saglimbeni** [comment] 2019-03-20 12:52
If you scroll down in the Transaction List screen, all the way down to the old transactions, then scroll back up to the top, can't you see the Card displaying the balance? Is this the issue?

**Comment by bitcoinuser** [comment] 2019-03-20 12:55
Yes, to scroll up again to see the card, I need to select the window in the part where there's transaction. On black part of window, if i scroll up, will appear the refresh icon to refresh transaction. 
I think shouldn't refresh the window, but instead should go to top.

**Comment by bitcoinuser** [comment] 2019-03-20 12:57
Remember that I only have two transaction on transaction list. So when I scroll down, I see a black space with no transaction info. If I scroll up using this space, will appear the refresh icon, instead of scroll up to top.

**Comment by bitschmidty** [comment] 2019-03-22 20:14
@bitcoinuser can you provide a video of your interactions? Or series of screenshots?

**Comment by domegabri** [comment] 2020-07-14 11:27
this looks like a duplicate of #78

**Closed by domegabri** 2020-07-14 11:27 UTC
Labels: bug
