### ISSUE TITLE
Authentication Required to Change Denomination of Watch-Only Wallet

### ISSUE THREAD

**Issue by noeljbass** [Blockstream/green_android#194] opened 2024-02-03 13:42 UTC
-Unable to change basic denomination from BTC to sats on watch only wallet

-Cannot change wallet name successfully either, i suspect because of the same auth issue

**Comment by jgriffiths** [comment] 2024-02-04 18:57
Hi,

All wallet metadata such as account names and transaction notes can only be changed by a full (non-watch-only) session. This is by design - if your watch-only details are leaked/obtained by an attacker, they are not able to grief you by deleting or altering this data.

The currency and pricing source settings are currently also only able to be changed by a full (non-watch-only) session. This is because fiat pricing limits are denominated in the wallets chosen currency. However, we will be allowing watch-only sessions to locally override these settings for display purposes in the next gdk (https://github.com/Blockstream/gdk) release 0.70.1, due in a few weeks. The wallet apps should support this functionality in their next release after that.

**Comment by angelix** [comment] 2024-03-16 07:44
Fixed in 8511d1ae496470f96b6b6105ddeca015bdd3aa9b
cc @noeljbass

**Closed by angelix** 2024-03-16 07:44 UTC
