### ISSUE TITLE
Green + Jade + Lightning -> Cannot add LN account without "paper hack" (Samsung S10e) 

### ISSUE THREAD

**Issue by Donach** [Blockstream/green_android#190] opened 2024-01-05 11:05 UTC
### Description

When trying to add "Create new account" in Green via Jade to add "Lightning Account", the QR code displayed has no white edges. This results in Jade never being able to properly scan the initial QR code to export the derived key for Green to use for the Lightning account.

### Version

Green v4.0.22; Jade FW version 1.0.26

### Steps to reproduce

1. Open Green
2. Unlock Jade in "Hardware Devices" wallet
3. Click 3 dots -> Create New Account
4. Select Lightning
5. Try to scan QR code with Jade
6. Fail

### Expected behaviour

The QR code should have white edges so it's scannable with Jade.

### Actual behaviour

QR code is impossible to scan.
Hack I used for it to work, was laying white paper all around the QR code, which then works just fine.

### Screenshots

![photo_2024-01-05_12-07-55](https://github.com/Blockstream/green_android/assets/39565367/b93e63fa-1f77-4bae-9f7f-8025233655b1)

### Device or machine

Samsung S10e, Android, Jade v1.0.26, Green v4.0.22 

### Additional info

After using my "paper hack", I was able to export the key to the Green wallet and use the Lightning as expected.

**Comment by angelix** [comment] 2024-01-05 19:13
Hi @Donach, thanks for reporting.

By looking at your photo, i can tell that something is wrong. Either you have an accessibility setting turned on or something else messes with the app's color. Could you please provide a photo or screenshot that shows the entire app interface? This will help us in diagnosing the problem more effectively.

You should expect to see a similar screen:
<img src="https://github.com/Blockstream/green_android/assets/631870/e27f720f-2c12-454f-96af-0d447541946d" width="300" />

**Comment by Donach** [comment] 2024-01-05 19:22
Hello!
Forgot to add I'm using Dark Theme in my system.
Funily though, other QR codes, like BTC receive address is rendered jsut fine with the white edge around the QR code.
I can post the screen later on - on your screen I can clearly see the white edge there, it's missing on mine...

**Comment by Donach** [comment] 2024-01-05 19:35
> > Hello! Forgot to add I'm using Dark Theme in my system. Funily though, other QR codes, like BTC receive address is rendered jsut fine with the white edge around the QR code. I can post the screen later on - on your screen I can clearly see the white edge there, it's missing on mine...
> 
>     * Is this issue also occurring with the QR code on the receive screen?
> 
>     * Is `Override force-dark` setting in Android enabled?
 
Yes, LN invoice looks 100% correct. 
No, I have 'force darkmode' set to OFF.

**Comment by Donach** [comment] 2024-01-06 13:25
> > > Hello! Forgot to add I'm using Dark Theme in my system. Funily though, other QR codes, like BTC receive address is rendered jsut fine with the white edge around the QR code. I can post the screen later on - on your screen I can clearly see the white edge there, it's missing on mine...
> > 
> > 
> > ```
> > * Is this issue also occurring with the QR code on the receive screen?
> > 
> > * Is `Override force-dark` setting in Android enabled?
> > ```
> 
> Yes, LN invoice looks 100% correct. No, I have 'force darkmode' set to OFF.

Ok just tested with Dark Mode OFF, and it did'nt solve anything for me.
Might be some combination of either the device (S10e), or the system version/OneUI from Samsung (v12 Android, 4.1 OneUI).
Here's how it looks.
![Screenshot_20240106_140608_Green](https://github.com/Blockstream/green_android/assets/39565367/4e618280-e276-49ae-8652-f317ed6c7685)

**Comment by angelix** [comment] 2024-03-16 07:45
@Donach Can you please confirm the issue is fixed with the latest version?

**Comment by Donach** [comment] 2024-03-16 08:01
Hello, sadly I can't , I don't have the Samsung s10e anymore...
works fine on my Pixel 7a now...

**Closed** 2024-03-18 11:06 UTC
